/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.gre.ma8521e.privatehirecars.GUI.Views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JEditorPane;
import uk.ac.gre.ma8521e.privatehirecars.Journey.Journey;

/**
 *
 * @author ma8521e
 */
public class CreateEnquiryView extends javax.swing.JPanel {

    /**
     * Creates new form CreateEnquiryVieww
     */
    public CreateEnquiryView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title_Pane = new javax.swing.JPanel();
        Name1 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        listofTrips = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        textBox = new javax.swing.JEditorPane();
        sendBtn = new javax.swing.JButton();
        Name4 = new javax.swing.JLabel();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_Pane.setBackground(new java.awt.Color(110, 89, 222));

        Name1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setText("Create Enquiry");

        Name2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setText("Is this regarding one of your early trips?");

        javax.swing.GroupLayout title_PaneLayout = new javax.swing.GroupLayout(title_Pane);
        title_Pane.setLayout(title_PaneLayout);
        title_PaneLayout.setHorizontalGroup(
            title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_PaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Name1)
                    .addComponent(listofTrips, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(633, Short.MAX_VALUE))
        );
        title_PaneLayout.setVerticalGroup(
            title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_PaneLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(Name1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(Name2)
                .addGap(11, 11, 11)
                .addComponent(listofTrips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel2.add(title_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, -1, -1));

        jScrollPane1.setViewportView(textBox);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 550, 200));

        sendBtn.setText("Send");
        jPanel2.add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 502, -1, -1));

        Name4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name4.setForeground(new java.awt.Color(51, 51, 51));
        Name4.setText("Question");
        jPanel2.add(Name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 930, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JComboBox getlistofTrips(){
        return this.listofTrips;
    }
    
    public JEditorPane getTextbox(){
        return this.textBox;
    }
    
    public JButton getSendBTn(){
        return this.sendBtn;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Journey> listofTrips;
    private javax.swing.JButton sendBtn;
    private javax.swing.JEditorPane textBox;
    private javax.swing.JPanel title_Pane;
    // End of variables declaration//GEN-END:variables
}
