/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.gre.ma8521e.privatehirecars.GUI.Views;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JSpinner;
import javax.swing.JTextField;

/**
 *
 * @author ma8521e
 */
public class CreateBooking extends javax.swing.JPanel {

    /**
     * Creates new form CreateBookinmg
     */
    public CreateBooking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_Pane = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        date = new javax.swing.JSpinner();
        to = new javax.swing.JTextField();
        from = new javax.swing.JTextField();
        Name5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Name6 = new javax.swing.JLabel();
        Cars = new javax.swing.JComboBox<>();
        checkAvailabilityButton = new javax.swing.JButton();
        confirmButton = new javax.swing.JButton();
        Name4 = new javax.swing.JLabel();
        finalPrice = new javax.swing.JLabel();
        Name8 = new javax.swing.JLabel();
        duration = new javax.swing.JLabel();
        Name9 = new javax.swing.JLabel();
        driver = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(930, 550));
        setMinimumSize(new java.awt.Dimension(930, 550));
        setPreferredSize(new java.awt.Dimension(930, 550));

        title_Pane.setBackground(new java.awt.Color(110, 89, 222));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Create Booking");

        Name3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name3.setForeground(new java.awt.Color(204, 204, 204));
        Name3.setText("To");

        Name2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name2.setForeground(new java.awt.Color(204, 204, 204));
        Name2.setText("From");

        Name1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name1.setForeground(new java.awt.Color(204, 204, 204));
        Name1.setText("Date");

        date.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        date.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));

        to.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        to.setMaximumSize(new java.awt.Dimension(149, 22));
        to.setMinimumSize(new java.awt.Dimension(149, 22));
        to.setPreferredSize(new java.awt.Dimension(149, 22));

        from.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        from.setMaximumSize(new java.awt.Dimension(149, 22));
        from.setMinimumSize(new java.awt.Dimension(149, 22));
        from.setPreferredSize(new java.awt.Dimension(149, 22));

        Name5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name5.setForeground(new java.awt.Color(204, 204, 204));
        Name5.setText("Car");

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Text", "Call", "Email" }));
        jComboBox1.setMaximumSize(new java.awt.Dimension(149, 22));
        jComboBox1.setMinimumSize(new java.awt.Dimension(149, 22));
        jComboBox1.setPreferredSize(new java.awt.Dimension(149, 22));

        Name6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name6.setForeground(new java.awt.Color(204, 204, 204));
        Name6.setText("Notification");

        Cars.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        Cars.setMaximumSize(new java.awt.Dimension(149, 22));
        Cars.setMinimumSize(new java.awt.Dimension(149, 22));
        Cars.setPreferredSize(new java.awt.Dimension(149, 22));

        javax.swing.GroupLayout title_PaneLayout = new javax.swing.GroupLayout(title_Pane);
        title_Pane.setLayout(title_PaneLayout);
        title_PaneLayout.setHorizontalGroup(
            title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_PaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Name)
                    .addGroup(title_PaneLayout.createSequentialGroup()
                        .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(title_PaneLayout.createSequentialGroup()
                                .addComponent(Name1)
                                .addGap(18, 18, 18)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(title_PaneLayout.createSequentialGroup()
                                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Name2)
                                    .addComponent(Name3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, 132, Short.MAX_VALUE)
                                    .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                        .addGap(33, 33, 33)
                        .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name6)
                            .addComponent(Name5))
                        .addGap(18, 18, 18)
                        .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(569, Short.MAX_VALUE))
        );
        title_PaneLayout.setVerticalGroup(
            title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_PaneLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1)
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name5)
                    .addComponent(Cars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(title_PaneLayout.createSequentialGroup()
                        .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name2)
                            .addComponent(from, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Name6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name3)
                            .addComponent(to, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        checkAvailabilityButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        checkAvailabilityButton.setText("Check availability");
  

        confirmButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        confirmButton.setText("Confim booking");


        Name4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name4.setText("Total Price: ");

        finalPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        finalPrice.setForeground(new java.awt.Color(204, 204, 204));
        finalPrice.setText("Check availability");

        Name8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name8.setText("Duration:");

        duration.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        duration.setForeground(new java.awt.Color(204, 204, 204));
        duration.setText("Check availability");

        Name9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name9.setText("Driver:");

        driver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        driver.setForeground(new java.awt.Color(204, 204, 204));
        driver.setText("Check availability");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkAvailabilityButton)
                        .addGap(18, 18, 18)
                        .addComponent(confirmButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Name9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(driver))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Name8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(duration))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Name4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(finalPrice)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(title_Pane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name4)
                    .addComponent(finalPrice))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(duration)
                    .addComponent(Name8))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name9)
                    .addComponent(driver))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton)
                    .addComponent(checkAvailabilityButton))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    public JButton getAvailabilityButton() {
        return this.checkAvailabilityButton;
    }

    public JButton getConfirmButton() {
        return this.confirmButton;
    }

    public JSpinner getDate() {
        return this.date;
    }

    public JLabel getDuration() {
        return this.duration;
    }

    public JLabel getDriver() {
        return this.driver;
    }

    public JLabel getFinalPrice() {
        return this.finalPrice;
    }


    public JTextField getTo() {
        return this.to;
    }

    public JTextField getFrom() {
        return this.from;
    }

    public JComboBox<String> getCarsDrop() {
        return this.Cars;
    }

    public JComboBox<String> getNotification() {
        return this.jComboBox1;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cars;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JLabel Name4;
    private javax.swing.JLabel Name5;
    private javax.swing.JLabel Name6;
    private javax.swing.JLabel Name8;
    private javax.swing.JLabel Name9;
    private javax.swing.JButton checkAvailabilityButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JSpinner date;
    private javax.swing.JLabel driver;
    private javax.swing.JLabel duration;
    private javax.swing.JLabel finalPrice;
    private javax.swing.JTextField from;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JPanel title_Pane;
    private javax.swing.JTextField to;
    // End of variables declaration//GEN-END:variables
}
