/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.gre.ma8521e.privatehirecars.GUI.Views;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author micae
 */
public class LoginView extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/uk/ac/gre/ma8521e/privatehirecars/GUI/Images/taxi_128x.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        iconLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();
        loginDebug = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home Page");
        setIconImages(null);
        setMaximumSize(new java.awt.Dimension(400, 508));
        setMinimumSize(new java.awt.Dimension(400, 508));
        setPreferredSize(new java.awt.Dimension(400, 508));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/ac/gre/ma8521e/privatehirecars/GUI/Images/taxi_128x.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        getContentPane().add(iconLabel, gridBagConstraints);

        usernameLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameLabel.setText("Username");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        getContentPane().add(usernameLabel, gridBagConstraints);

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        passwordLabel.setText("Password");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        getContentPane().add(passwordLabel, gridBagConstraints);

        usernameTxt.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        usernameTxt.setMinimumSize(new java.awt.Dimension(102, 27));
        usernameTxt.setPreferredSize(new java.awt.Dimension(102, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        getContentPane().add(usernameTxt, gridBagConstraints);

        passwordTxt.setMinimumSize(new java.awt.Dimension(102, 27));
        passwordTxt.setPreferredSize(new java.awt.Dimension(102, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(7, 0, 0, 0);
        getContentPane().add(passwordTxt, gridBagConstraints);

        loginButton.setText("Login");
        loginButton.setMaximumSize(new java.awt.Dimension(80, 23));
        loginButton.setMinimumSize(new java.awt.Dimension(80, 23));
        loginButton.setPreferredSize(new java.awt.Dimension(80, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 3, 3);
        getContentPane().add(loginButton, gridBagConstraints);

        signupButton.setText("Sign up");
        signupButton.setMaximumSize(new java.awt.Dimension(80, 23));
        signupButton.setMinimumSize(new java.awt.Dimension(80, 23));
        signupButton.setPreferredSize(new java.awt.Dimension(80, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.insets = new java.awt.Insets(17, 2, 3, 8);
        getContentPane().add(signupButton, gridBagConstraints);

        loginDebug.setText("Login into debug account");
        loginDebug.setMaximumSize(new java.awt.Dimension(180, 23));
        loginDebug.setMinimumSize(new java.awt.Dimension(180, 23));
        loginDebug.setPreferredSize(new java.awt.Dimension(180, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.insets = new java.awt.Insets(17, 2, 3, 8);
        getContentPane().add(loginDebug, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Application only works within the UniGre network");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        getContentPane().add(jLabel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getIcon() {
        return this.iconLabel;
    }

    public JButton getLoginButton() {
        return this.loginButton;
    }

    public JButton getSignupButton() {
        return this.signupButton;
    }

    public JLabel getpasswordLabel() {
        return this.passwordLabel;
    }

    public JPasswordField getPasswordTxt() {
        return this.passwordTxt;
    }

    public JLabel getUsernameLbl() {
        return this.usernameLabel;
    }

    public JTextField getUsernameTxt() {
        return this.usernameTxt;
    }

    public JButton getLoginDebugBtn(){
        return this.loginDebug;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton loginDebug;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton signupButton;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JTextField usernameTxt;
    // End of variables declaration//GEN-END:variables
}
