/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.ac.gre.ma8521e.privatehirecars.GUI.Views;

/**
 *
 * @author micae
 */
public class Profile extends javax.swing.JPanel {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        title_Pane = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        lbl_PhoneNumber = new javax.swing.JLabel();
        lbl_YOB = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title_Pane.setBackground(new java.awt.Color(110, 89, 222));

        Name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setText("Micael Jose Ribeiro Araujo");

        lbl_PhoneNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_PhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_PhoneNumber.setText("Phone Number: 072323 123432");

        lbl_YOB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_YOB.setForeground(new java.awt.Color(255, 255, 255));
        lbl_YOB.setText("Year of Birth : 1997");

        Name1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Name1.setForeground(new java.awt.Color(204, 204, 204));
        Name1.setText("Passenger");

        javax.swing.GroupLayout title_PaneLayout = new javax.swing.GroupLayout(title_Pane);
        title_Pane.setLayout(title_PaneLayout);
        title_PaneLayout.setHorizontalGroup(
            title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_PaneLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_YOB)
                    .addComponent(lbl_PhoneNumber)
                    .addGroup(title_PaneLayout.createSequentialGroup()
                        .addComponent(Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 579, Short.MAX_VALUE)
                        .addComponent(Name1)))
                .addContainerGap())
        );
        title_PaneLayout.setVerticalGroup(
            title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(title_PaneLayout.createSequentialGroup()
                .addGroup(title_PaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(title_PaneLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(Name))
                    .addGroup(title_PaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Name1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_PhoneNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_YOB)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.add(title_Pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 930, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 550));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_PhoneNumber;
    private javax.swing.JLabel lbl_YOB;
    private javax.swing.JPanel title_Pane;
    // End of variables declaration//GEN-END:variables
}
